services:
  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ~/data/redis:/data
    user: "1000:1000"
    depends_on:
      - redisinsight
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:2.68
    ports:
      - "127.0.0.1:5540:5540"
    restart: unless-stopped

  mysql:
    image: mysql:8.0-bookworm
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql.conf:/etc/mysql/conf.d/mysql.cnf
      - ~/data/mysql/data:/var/lib/mysql
      - ~/data/mysql/log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    user: "1000:1000"
    depends_on:
      - adminer
    restart: unless-stopped

  adminer:
    image: adminer:5.2.1-standalone
    ports:
      - "127.0.0.1:3307:8080"
    restart: unless-stopped

  alist:
    image: xhofe/alist:v3.44.0-aio
    ports:
      - "5244:5244"
    volumes:
      - ~/data/alist:/opt/alist/data
      - ~/data:/mnt/data
    environment:
      PUID: 1000
      PGID: 1000
    restart: unless-stopped

  kit:
    image: debian:bookworm-slim
    depends_on:
      - redis
      - mysql
      - alist

  bookworm-slim:
    image: debian:bookworm-slim

  bookworm:
    image: debian:bookworm

  python-slim:
    image: python:3.12-slim-bookworm

  python:
    image: python:3.12-bookworm
